### ISSUE TITLE
ros requirement

### ISSUE THREAD

**Issue by Zippen-Huang** [stereolabs/zed-yolo#1]
Dear sir, can you support a zed-yolo-3D ROS wrapper, I want to use the software package in ROS(robot operating system), and I do not success , thank you very much!

**Comment by Zippen-Huang** [comment]
sir，here I face two questions: 1)if I used zed-yolo, can I read image message from zed in other ros node. 2)how to modify makfile in zed-yolo to cmakelist in ros. thank you!

**Comment by griz1112** [comment]
https://github.com/PeteHeine/DarknetROS
