### ISSUE TITLE
darkent

### ISSUE THREAD

**Issue by Docker300** [stereolabs/zed-yolo#10]
darknet.sln issue

**Comment by AlexeyAB** [comment]
@Docker300 You can try to build this repository https://github.com/AlexeyAB/darknet by using Cmake, there will be created `uselib.exe` that uses ZED-camera:
`uselib.exe data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera`

**Comment by Docker300** [comment]
I am unable to find uselib.exe file in darknet folder when I compiled this repository according to the instructions given in How to compile on Windows (using vcpkg)

> If you have already installed Visual Studio 2015/2017/2019, CUDA > 10.0, cuDNN > 7.0, OpenCV > 2.4, then compile Darknet by using C:\Program Files\CMake\bin\cmake-gui.exe as on this IMAGE: Configure -> Optional platform for generator (Set: x64) -> Finish -> Generate -> Open Project -> x64 & Release -> Build -> Build solution

I have Visual Studio 2017, CUDA 10.0, cuDNN  7.5, OpenCV 3.4.0, CMAKE 3.13.4

When I use uselib.exe data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera
it gives following error 
> 'uselib.exe' is not recognized as an internal or external command,
operable program or batch file.
Where is this file located?

**Comment by AlexeyAB** [comment]
If you compiled with **x64 & Release** https://hsto.org/webt/uh/fk/-e/uhfk-eb0q-hwd9hsxhrikbokd6u.jpeg
then `uselib.exe` will be created in the `Release` folder.

**Comment by Docker300** [comment]
Thank You for the help
I am newbie.  I compiled Darknet.sln with x64 & Release. and when I use  

> uselib.exe data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera

 in command prompt it give error

> uselib.exe System error 

> pthreadVC2.dll does not exist so the code execution can not proceed. So reinstall the program can resolve this issue.

![uselib system error](https://user-images.githubusercontent.com/50576340/57983765-819dea00-7a90-11e9-9780-6b07c85ae27f.JPG)

I don't know why is it giving this error because project is successfully build
 
![buildsuccess](https://user-images.githubusercontent.com/50576340/57983806-da6d8280-7a90-11e9-895b-68e30eeabac7.JPG)

But pthread.h is also not found in CMAKE. 
![Dnet](https://user-images.githubusercontent.com/50576340/57983817-025ce600-7a91-11e9-947a-5d1ba6541153.JPG)

Would you please guide me ?
Am I getting uselib.exe-System error because pthread.h is not found in CMAKE? 
If it is the reason then how can I solve it?
Do I need to re-install the CMAKE? or Do I need to make any change in any file to solve this issue?




>

**Comment by AlexeyAB** [comment]
1. Copy `darklib.dll` and `uselib.exe` from `darknet/Release` folder to the `darknet/` root folder.

2. Also copy `pthreadGC2.dll` and `pthreadVC2.dll` from `darknet\3rdparty\pthreads\bin\` folder to the `darknet/` root folder.

3. Download https://pjreddie.com/media/files/yolov3.weights to the `darknet/` root folder.

4. Then run `uselib.exe data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera`
    **in the `darknet/` root folder.**

**Comment by Docker300** [comment]
Thank You for the detailed reply :) 

When I run uselib.exe data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera
I get this error

> input image or video filename: **ZED 3D Camera NOT ENOUGH GPU MEMORY**
>  Error: ZED Camera should be connected to USB 3.0. And ZED_SDK should be installed.

But ZED camera is connected and ZED SDK is also installed in  C:\Program Files (x86)\ZED SDK 
(CMAKE has also detected ZED SDK at the same location C:\Program Files (x86)\ZED SDK)

I do not get this error when I run ZED SDK Example projects.
But I get this error when I run ZED-YOLO.

Would you please tell me that why am I getting  
> ZED 3D Camera NOT ENOUGH GPU MEMORY

error and how should I solve it?

I am using Nvidia GeForce 840M and latest version of ZED SDK 2.8

![d1](https://user-images.githubusercontent.com/50576340/58095669-82f52100-7c0e-11e9-8120-dfa706b9826b.JPG)
.
.
.
![d2](https://user-images.githubusercontent.com/50576340/58095699-8e484c80-7c0e-11e9-847b-5cb67ed2d87a.JPG)

**Comment by AlexeyAB** [comment]
It seems that you don't have enough GPU-RAM to run full yolov3-model.

Try to run tiny model:

* Download: https://pjreddie.com/media/files/yolov3-tiny.weights

* run: 

`uselib.exe data/coco.names cfg/yolov3-tiny.cfg yolov3-tiny.weights zed_camera`

**Comment by Docker300** [comment]
Thank You.  Although, It is not showing "Not enough GPU" error now.
But it gives another error "ZED 3D Camera Failed to setup" and stops when I run either Yolo3 or Yolo-Tiny

I don't know that why it is giving this error .
For testing the camera, I opened ZED explorer to check if camera is setup or not. In ZED explorer it opens the camera, it means there is no issue related to camera setup. Then why it is giving this error here when I run it for YOLO 

Please guide me
Do I need to make some changes in any file?

![image](https://user-images.githubusercontent.com/50576340/58237076-4268e500-7d7f-11e9-8b2c-9744da99692e.png)

**Comment by AlexeyAB** [comment]
Try to un-comment this line and recompile: https://github.com/AlexeyAB/darknet/blob/9c9344a1ff4541499c8f69ea997be5145b4e1de3/src/yolo_console_dll.cpp#L340

What GPU do you use?

**Comment by Docker300** [comment]
Line# 340 in yolo_consol_dll.cpp is already commented.
I am using Nvidia GeForce 840M (GPU).

**Comment by AlexeyAB** [comment]
Un-comment, i.e. change this line:
`//init_params.sdk_cuda_ctx = (CUcontext)detector.get_cuda_context();`
to this
`init_params.sdk_cuda_ctx = (CUcontext)detector.get_cuda_context();`

**Comment by Docker300** [comment]
I did it but facing the same issue :(

**Comment by Docker300** [comment]
I am getting this error and tried to fix it many times.

>  ZED (Init) >> ERROR: Executable was designed for SDK v2.8.0 / installed v2.8.1
> CAMERA FAILED TO SETUP

Although, It build the project successfully but does not show any output due to this error.
I am facing this problem not only in YOLO but also in all other ZED examples now.  Problem is still there after reinstalling the SKD
Would you please guide me?

**Comment by AlexeyAB** [comment]
@Docker300 Try to recompile Darknet Yolo

**Comment by Docker300** [comment]
I tried every possible solution except reinstalling windows... 
After re-installing Zed-SDK I also re-installed cuda 10.0 ( after deleting its old installation)
 I recomiled Darknet YOLO but getting same message 
![image](https://user-images.githubusercontent.com/50576340/58820603-ffa3e880-866d-11e9-8378-4e3d8f8b53ba.png)

When I run C:\Program Files (x86)\ZED SDK\tools\ZED Depth Viewer.exe
It shows the camera.
But
I don't know that why it fails to start camera when I run the code either darknet-YOLO or Zed master examples.             
I have been trying to solve this issue since last two weeks.
Please suggest me some solution.

**Comment by AlexeyAB** [comment]
> ZED (Init) >> ERROR: Executable was designed for SDK v2.8.0 / installed v2.8.1
> CAMERA FAILED TO SETUP
> 

What is the current SDK version do you use?

It seems that you try to run old SDK (2.8.0) exe-files

So it seems that somewhere there are still old and new versions of ZED SDK 

1. Try to delete all files of old SDK

2. Also try to delete your Darknet, download it again and compile again.

**Comment by Docker300** [comment]
I did all these steps and I'm using SDK 2.8.1 now.
After deleting SDK 2.8.0 it does NOT give message  

> ZED (Init) >> ERROR: Executable was designed for SDK v2.8.0 / installed v2.8.1

But 

> CAMERA FAILED TO SETUP

problem is still there when I run ZED Examples.

Also, gives the same message message with I run YOLO after downloading and compiling it.
Although, it does not give any error in build
But I don't know that whey it fails to run camera in code or SDK
while camera is successfully detected by zed explorer.exe

**Comment by Docker300** [comment]
Thank  You, It is working now.
Would you please tell me that 
To train ZED-YOLO 3D ( with depth estimation for 3D object detection)

- Do I have to use labeled 3D image dataset or labeled 2D image dataset?
 Or
- Labeled dataset of both 2D images and  labeled dataset of its Depth images?

**Comment by AlexeyAB** [comment]
You should use 2D labels as usual. ZED will estimate 3D coords automatically.

**Comment by Docker300** [comment]
Okay.
Thank You :)

**Comment by Docker300** [comment]
Same command is used to train the yolo-tiny with depth estimation for ZED?
> darknet.exe detector train data/obj.data yolov3-tiny.cfg darknet53.conv.74
 Or
we have to use different command?

**Comment by AlexeyAB** [comment]
Read: https://github.com/AlexeyAB/darknet#how-to-train-tiny-yolo-to-detect-your-custom-objects

**Comment by Docker300** [comment]
Please guide me
In YOLO-ZED
What is **_x_** and **_y_**?
Is it height and width of bounding box?
and How **z** is calculated?
Does ZED_YOLO extracts the distance or **_z_** (depth) value by taking the center of bounding box(width/2, height/2) of detected image?

**Comment by adujardin** [comment]
The current ZED Yolo simply takes the 2D detector output and compute the 3D world coordinates from the depth map computing at runtime during the inference. 

The training phase doesn't take into account the 3D at all. It's just a regular Yolo 2D detector

**Comment by Docker300** [comment]
Okay. Thank You
Would you please explain about x, y and z value here?
 _**x**_, _**y**_ values indicate the width and height of bound box  while **_z_** shows the distance from camera? 

![image](https://user-images.githubusercontent.com/50576340/59364474-dcfe8780-8d71-11e9-9db6-905ac4797730.png)

**Comment by AlexeyAB** [comment]
@Docker300 `x, y, z` - are 3D coordinates of center of object (measured in meters relative to left camera)

**Comment by Docker300** [comment]
Okay. Thank You

**Comment by Docker300** [comment]
For training
1. Is it okay If image size is 450 X 600 (instead of 450 x 450 or 600 x 600) ?
2. In this case, should we also change  the width and height in .cfg file according to our image size?
3. if Yes then should we change other parameters according to 450 x 600 image size?

**Comment by Docker300** [comment]
I have trained YOLO on my own dataset.  I have to use zed camera. For this, when I use uselib.exe.
On test image and video files, **it does not show labels and depth info when I run uselibe.exe** it only draws bounding boxes
![1_Label_No](https://user-images.githubusercontent.com/50576340/59740829-34d24c80-92a4-11e9-9f77-7be05320d56f.JPG)

But
When I run  darknet.exe it shows the bounding boxes with labels like this
![1_label](https://user-images.githubusercontent.com/50576340/59740798-1d935f00-92a4-11e9-8f43-5a2e3c100502.JPG)

What would be the issue?

**Comment by AlexeyAB** [comment]
Because you use wrong names-file in your command:
`uselib.exe data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera`

It can show depth info only on **Video**-stream from ZED-camera.

**Comment by Docker300** [comment]
You are right. Thank You  :)

**Comment by umair-nazeer** [comment]
I  can't able to use wingpudll compiled by visual studio the file do exists at path and os.exists also returns true but CDLL is not able to open the dll picture is attached please check
![ss](https://user-images.githubusercontent.com/33023973/61992707-1158a980-b07b-11e9-9440-efac81ff1f79.PNG)

**Comment by Whisper94** [comment]
@AlexeyAB
Hello. If I try to use this command `uselib.exe data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera` then I'll get following error 
![image](https://user-images.githubusercontent.com/60612672/80674541-7c278d00-8ab2-11ea-88e8-d59defaa7234.png)

Bevor I've copied opencv_world3410.dll from opencv-folder because it couldn't be found from darknet.

Thank you!

**Comment by ibrahimaa9** [comment]
why it doesn't work 
![Screenshot (5)](https://user-images.githubusercontent.com/29759602/82116687-4f42cd80-9774-11ea-8bc3-fed8bfa99ff4.png)

**Comment by leemaru** [comment]
> Thank You, It is working now.
> Would you please tell me that
> To train ZED-YOLO 3D ( with depth estimation for 3D object detection)
> 
> * Do I have to use labeled 3D image dataset or labeled 2D image dataset?
>   Or
> * Labeled dataset of both 2D images and  labeled dataset of its Depth images?

How did you get this to work? I am having the same error. But I am on a brand new PC with RTX2070, so I know I have enough RAM and the proper GPU.

**Comment by FatemehEsfahani** [comment]
I get pthreadvc2.dll not found. How I can fix it?
