### ISSUE TITLE
The specific module cannot be found in windows

### ISSUE THREAD

**Issue by dephaniehe** [stereolabs/zed-yolo#13]
When I use the darknet_zed.py in Windows, it prints error:
Traceback (most recent call last):
  File "darknet_zed.py", line 106, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\software\python\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Does anyone know the solution?

**Comment by Franksign** [comment]
do you resolved? I'm having the same issue with the python wrapper

**Comment by sarimmehdi** [comment]
Were you able to find a solution to this? Please let us know. Thanks!

**Comment by jackie0930** [comment]
I also have the same question
