### ISSUE TITLE
CMAKE ERREO: ZED SDK not enabled, since it requires CUDA

### ISSUE THREAD

**Issue by TEOEFW** [stereolabs/zed-yolo#14]
hi @adujardin
     i got a erreo when i cmake .. said  ZED SDK not enabled, since it requires CUDA
can you tell me whats wrong with it?

**Comment by Scarf195** [comment]
Hi, I have the same problem. Did you solve that?

**Comment by 1343464520** [comment]
Hi, I have the same problem too. Did you solve that?

**Comment by obraun-sl** [comment]
ZED SDK requires CUDA, therefore it's a mandatory requirement. 
You need to have CUDA installed on your PC.

**Comment by adujardin** [comment]
You may need to update cmake on Ubuntu for the CUDA detection to work reliably, [see here](https://github.com/stereolabs/zed-yolo#cmake)
