### ISSUE TITLE
error while loading shared libraries: libdarknet

### ISSUE THREAD

**Issue by TEOEFW** [stereolabs/zed-yolo#15]
dear adujardin
       when i run ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera it comes out ./uselib: error while loading shared libraries: libdarknet.so: cannot open shared object file: No such file or directory 
       then i am confused,do you have any idea what am i doing wrong ?

**Comment by abhimanyuchadha96** [comment]
Hey, how did you solve this?
