### ISSUE TITLE
Loading weights from yolov3-tiny.weights...Couldn't open file: yolov3-tiny.weights

### ISSUE THREAD

**Issue by TEOEFW** [stereolabs/zed-yolo#16]
dear friend! when i ran ./darknet_zed ../../libdarknet/data/coco.names ../../libdarknet/cfg/yolov3-tiny.cfg yolov3-tiny.weights
came out of the message
Loading weights from yolov3-tiny.weights...Couldn't open file: yolov3-tiny.weights
Segmentation fault (core dumped)

**Comment by machenxiang** [comment]
> dear friend! when i ran ./darknet_zed ../../libdarknet/data/coco.names ../../libdarknet/cfg/yolov3-tiny.cfg yolov3-tiny.weights
> came out of the message
> Loading weights from yolov3-tiny.weights...Couldn't open file: yolov3-tiny.weights
> Segmentation fault (core dumped)
Thanks in advance. Did you solve the problem. If you did can you tell me how to fix it?

Did
