### ISSUE TITLE
Image capture 

### ISSUE THREAD

**Issue by Wombat68** [stereolabs/zed-yolo#22]
Hello again,

I want to capture images from the "uselib" application and also I want to save the information (bounding box, depth and confidence) to a txt file or a json file. Should I do some changes to the darknet.sln code or is there another way to do it.

**Comment by AlexeyAB** [comment]
@MarcNehme Hi,

If you use `./uselib` application, then you can edit this file: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp
