### ISSUE TITLE
./uselib not found

### ISSUE THREAD

**Issue by anathema43** [stereolabs/zed-yolo#34]
hi,
I compiled  https://github.com/AlexeyAB/darknet using make file with,
cuda=1
Cudnn=1
cudnn_half=1
opencv=1
ZED_CAMERA=1

when i try the command LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov4.cfg cfg/yolov4.weights zed_camera
I get error uselib not found.
is the uselib generated anywhere else?
![Screenshot from 2020-09-17 15-15-02](https://user-images.githubusercontent.com/37859650/93454406-95fa2d00-f8f8-11ea-94a5-e23468c009b3.png)

please let me know if I am missing anything

**Comment by MahmoudF98** [comment]
Set LIBSO to 1 in the Makefile:

LIBSO=1
