### ISSUE TITLE
ValueError: NULL pointer access when object is detected

### ISSUE THREAD

**Issue by rykymai** [stereolabs/zed-yolo#36]
![Schermata 2020-10-28 alle 14 50 12](https://user-images.githubusercontent.com/28538355/97444858-e4a1da80-192c-11eb-992e-764d4faa2d80.png)
I have this issuse every time it detects a person, i'm testing it with yolov3-tiny, if i run instead ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera it works

**Comment by rykymai** [comment]
solved

**Comment by niemiaszek** [comment]
@rykymai how did you solve this?

**Comment by niemiaszek** [comment]
Okay, I solved it myself. Next time, please, explain the solution, to help people facing the same problem. Solution is provided by AlexeyAB [there](https://github.com/AlexeyAB/darknet/issues/6322#issuecomment-663215126). You have to change class DETECTION to new format. One used inn darknet_zed.py is outdated. I will prepere pull request, hopefully someone will notice it.

**Comment by yuxuan-wang-tj** [comment]
@niemiaszek I can't solve this problem, could you give me some details ?

**Comment by niemiaszek** [comment]
Do you have new version of this repository with my Pull Request? It solved the problem for me and some other people

**Comment by yuxuan-wang-tj** [comment]
@niemiaszek I have replaced darnet.py in libdarnet with the latest version, and I have changed the class DETECTION in darnet_zed.py to new format. However, The problem still exists .

**Comment by niemiaszek** [comment]
Do you use [Alexey darknet repo](https://github.com/AlexeyAB/darknet) for build, libs etc. or do you use the one provided in this repo? Darknet in zed-yolo repo has very old code in it so it might not work with the structure from my PR, didn't test it. I built darknet with instructions from Alexey repo and then changed paths in this zed-yolo repo to match Darknet. I have done this installation month ago and it was working with no problem for me

**Comment by yuxuan-wang-tj** [comment]
@niemiaszek Thank you very much. I have solved the problem after I followed the method you said. I truly appreciate your timely help.

**Comment by niemiaszek** [comment]
@yuxuan-wang-tj You are welcome 😄
