### ISSUE TITLE
darknet issue

### ISSUE THREAD

**Issue by vbcomp** [stereolabs/zed-yolo#44]
Every time I try to execute darknet.exe I keep getting an error saying the code execution cannot proceed because hdf5.dll was not found. Can someone please help me understand what this means and how to fix it.

**Comment by e101sg** [comment]
I am getting same error on Windows 10. It was working correctly...not sure what happen. Now when ever run
`darknet.exe detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights` 
getting the hdf5.dll error. Please advise.
