### ISSUE TITLE
libdarknet compiling error, ./src/im2col_kernels.cu error

### ISSUE THREAD

**Issue by chlwnsgh5050** [stereolabs/zed-yolo#47]
Hi i have zed2
and ubuntu 18.04 cuda 10.2 cudnn 8.0.1 python3
i am trying to compile libdarket for zed-yolo python but i have some trouble
when i make -j4

and this is my error code

./src/im2col_kernels.cu:109:18: warning: "/*" within comment [-Wcomment]
                 //*data_col_ptr = (h >= 0 && w >= 0 && h < height && w < width) ?
                   
./src/im2col_kernels.cu:352:30: warning: "/*" within comment [-Wcomment]
                             //*bit32_ptr = bit_mask;
                               
./src/im2col_kernels.cu:1047:6: warning: "/*" within comment [-Wcomment]
     //*((uint64_t *)(A_s + (local_i*lda + k) / 8)) = *((uint64_t *)(A + (i_cur*lda + k) / 8));    // weights
       
./src/maxpool_layer_kernels.cu(93): warning: variable "maxpool_status" was set but never used

./src/im2col_kernels.cu(494): error: identifier "__shfl" is undefined

./src/im2col_kernels.cu(515): warning: function "__ballot"
/usr/local/cuda-10.2/include/sm_20_intrinsics.h(405): here was declared deprecated ("__ballot() is not valid on compute_70 and above, and should be replaced with __ballot_sync().To continue using __ballot(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")

./src/im2col_kernels.cu(439): warning: variable "tmp_s" was declared but never referenced

./src/im2col_kernels.cu(440): warning: variable "tmp256_s" was declared but never referenced

./src/im2col_kernels.cu(593): warning: function "__ballot"
/usr/local/cuda-10.2/include/sm_20_intrinsics.h(405): here was declared deprecated ("__ballot() is not valid on compute_70 and above, and should be replaced with __ballot_sync().To continue using __ballot(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")

./src/im2col_kernels.cu(824): warning: variable "num_blocks" was declared but never referenced

./src/im2col_kernels.cu(1084): error: identifier "__shfl_xor" is undefined

./src/im2col_kernels.cu(1140): error: identifier "__shfl" is undefined

./src/im2col_kernels.cu(1170): error: identifier "__shfl" is undefined

./src/im2col_kernels.cu(1116): warning: variable "h" was declared but never referenced

./src/im2col_kernels.cu(1416): warning: variable "k" was declared but never referenced

./src/im2col_kernels.cu(1481): error: identifier "__shfl_down" is undefined

./src/im2col_kernels.cu(1589): warning: variable "weights_pre_index" was declared but never referenced

./src/im2col_kernels.cu(1820): warning: reference is to variable "fil"
(1779): here -- under old for-init scoping rules it would have been variable "fil"
(1809): here

./src/im2col_kernels.cu(1847): warning: reference is to variable "fil"
(1779): here -- under old for-init scoping rules it would have been variable "fil"
(1809): here

./src/im2col_kernels.cu(1868): warning: reference is to variable "fil"
(1779): here -- under old for-init scoping rules it would have been variable "fil"
(1809): here

./src/im2col_kernels.cu(1859): warning: variable "input_index" was declared but never referenced

./src/im2col_kernels.cu(1860): warning: variable "weights_index" was declared but never referenced

./src/im2col_kernels.cu(1844): warning: variable "src_index" was declared but never referenced

./src/im2col_kernels.cu(1845): warning: variable "input_byte" was declared but never referenced

./src/im2col_kernels.cu(1902): warning: reference is to variable "fil"
(1779): here -- under old for-init scoping rules it would have been variable "fil"
(1809): here

./src/im2col_kernels.cu(615): warning: function "remove_bit" was declared but never referenced

./src/im2col_kernels.cu(621): warning: function "set_bit" was declared but never referenced

./src/im2col_kernels.cu(848): warning: function "broadcast_bit_1_to_64" was declared but never referenced

./src/im2col_kernels.cu(864): warning: function "xnor_int128" was declared but never referenced

./src/im2col_kernels.cu(883): warning: function "popcnt_256" was declared but never referenced

5 errors detected in the compilation of "/tmp/tmpxft_00005493_00000000-6_im2col_kernels.cpp1.ii".
Makefile:142: recipe for target 'obj/im2col_kernels.o' failed
make: *** [obj/im2col_kernels.o] Error 1
make: *** 끝나지 않은 작업을 기다리고 있습니다....
./src/maxpool_layer_kernels.cu: In function ‘void forward_maxpool_layer_gpu(maxpool_layer, network_state)’:
./src/maxpool_layer_kernels.cu:93:15: warning: variable ‘maxpool_status’ set but not used [-Wunused-but-set-variable]
         cudnnStatus_t maxpool_status;
               ^~~~~~~~~~~~~~

how can i handle im2col_kenels.cu ??  please help me

**Comment by TweepingH** [comment]
emm,,may because zed-yolo only supports cudnn v3-v7
