### ISSUE TITLE
how to use yolov5 in zed

### ISSUE THREAD

**Issue by Ethan2020-de** [stereolabs/zed-yolo#48]
I had a ZED2 Camera, want to use it in yolov5, but i can't find a good way to use the functions zed same time.

**Comment by lxxdd** [comment]
hi , do you successful with yolov4?I want to do it with v4 too .but I do not know how to do

**Comment by Ethan2020-de** [comment]
hi, in stereo lab website has the sample for yolov4

lxxdd ***@***.***> 于2021年4月15日周四 下午3:37写道：

**Comment by lxxdd** [comment]
thank you，can you give me the Internet site

**Comment by Ethan2020-de** [comment]
you can see this,https://github.com/stereolabs/zed-yolo

lxxdd ***@***.***> 于2021年4月16日周五 上午4:56写道：
