### ISSUE TITLE
Cannot find darknet.exe file in order to train YOLOv2 on Pascal data

### ISSUE THREAD

**Issue by FleetingA** [stereolabs/zed-yolo#49]
I have been following the instructions to install and configure Darknet on Windows 10 listed here: https://github.com/AlexeyAB/darknet/tree/47c7af1cea5bbdedf1184963355e6418cb8b1b4f#how-to-train-pascal-voc-data

I have downloaded all the programs that I need, including CUDA, CMake, Visual Studio, cuDNN, OpenCV.

When I get to the point of training on the Pascal data and type in darknet.exe detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23 in the command line, I get the error:

"darknet.exe : The term 'darknet.exe' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again."

Any idea how this could be fixed?

**Comment by alperensenyigit** [comment]
I have faced same error a few minutes ago. Did you solve that?

![Screenshot_1](https://user-images.githubusercontent.com/75634684/143783186-a20392a9-93f1-4d5f-b7fa-3c84bfd3f1c7.png)
