### ISSUE TITLE
Segmentation fault (core dumped) Problem

### ISSUE THREAD

**Issue by ahmettarhan** [stereolabs/zed-yolo#51]
I am trying to run darknet_zed. py file but  I keep getting Segmentation fault (core dumped) error. I tried to figure out the problem, I think the problem is within the detect() function. I printed the 253rd row which is " if dets[j].prob[i] > 0: " and I attached the result.
![1](https://user-images.githubusercontent.com/42208681/121775545-0df83980-cb91-11eb-920a-e9ee5057583b.png)

**Comment by a741419244** [comment]
可能是内存泄露，栈满了，产生了非法访问内存
